### ISSUE TITLE
USB Rufus Howto update

### ISSUE THREAD

**Issue by Dbzs** [rockstor/rockstor-doc#193]
Rufus how to is based on older version and while the options are still valid in version 3.4 how and when you select them has changed.  Need to update pictures and text to match new version.  Opening this so I can work it.

**Comment by phillxnet** [comment]
@Dbzs Thanks for opening this issue and stepping up to improve our docs. It would be great to have this howto updated.

**Comment by Dbzs** [comment]
Working on it now, and learning git on the fly, think it will all work out.

**Comment by Dbzs** [comment]
@phillxnet Just finished the update and hopefully opened my first pull request.  If things don't look right I'd appreciate any feedback.

**Comment by phillxnet** [comment]
@Dbzs pull request wise that looks just fine. Well done. We just need a review / second set of eyes and we can pop that in (given any suggested changes are worked through).
I've added a "needs review" label to the pull request and we can take it from there.
Can't do myself just yet however as otherwise engaged but we should be able to get to this fairly quickly hopefully.
Thanks again for tackling this one. Much appreciated.

**Comment by phillxnet** [comment]
Closing as fixed by
"Rufus ver3.4 update" #194

Thanks @Dbzs and well done on a nicely presented pull request.
Much appreciated.
The published version won't be available until the rockstor-doc repo is pushed out the main webserver however.

**Comment by Dbzs** [comment]
Good news, thank you. Glad I can help.
