### ISSUE TITLE
4th plus depth of navigation lost in overview

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#294]
Post #290 we struggle to locate the current doc view in our overview table of contents. An example, possibly the only one, is in:

docs/interface/system/identity/users.html#users-view

It may not be practical but would be desirable if we could maintain an indication of where this location resides overall in the docs. This is thought to be down to our limit of overview expansion to 3: i.e. top, second level deep, third level deep. And the fourth is apparently no longer expressed in the TOC.

This is non critical and may represent a 'depth too far' for practically displaying in the space available. But noting here just in case this took someones fancy for a project improvement.

**Comment by FroggyFlox** [comment]
@phillxnet , with regards to:

> This is thought to be down to our limit of overview expansion to 3: i.e. top, second level deep, third level deep. And the fourth is apparently no longer expressed in the TOC.

This one is my own doing, as I set a max depth for our TOC in the left sidebar to 3 in #290. Our current style is not ready for more than 3 levels in my opinion, so that's why I limited it at 3.
I was planning on addressing this style issue in a future issue/PR, but it seems you just beat me to it with this current issue ;-) . We, for instance, have a 40 px padding for **each** depth in our TOC, which adds up very quickly and is unnecessary.

Another option is to include breadcrumbs at the top... might be worth investigating.

**Comment by FroggyFlox** [comment]
I've now finally found some time to give that one a try and I opted for a simple fix that I had in mind for a little while. Indeed, the reason I limited the max depth for our sidebar toc to 3 was due to the relatively high `padding-left` we had in our style for **each** depth of our toc. For a level 4, for instance, this means we have 3 x 20 px = 60 px. As our titles are not that brief (maybe should be the focus of a separate issue), this led to some excessive space used.

> docs/interface/system/identity/users.html#users-view

This is how this page currently looks:
![image](https://user-images.githubusercontent.com/30297881/131254693-d7eb4518-0a3d-4390-8131-3f8462e47a39.png)

If we are to use a more reasonable `padding-left`, we can increase the max depth for our toc to 4 (or even more), and it looks like:
![image](https://user-images.githubusercontent.com/30297881/131254718-68d71719-80a0-4ad0-8bca-7cc96fa0b1ec.png)

We can still see how we can better emphasize the current location to the user (maybe some subtle but impactful styling on our `.current` elements), without having to work a breadcrumbs system...

**Comment by phillxnet** [comment]
@FroggyFlox Well done, that's much better. Nice.

**Comment by FroggyFlox** [comment]
@phillxnet , I couldn't set on the best way to emphasize the current entry in the toc, so I settled with a simple bold font weight for the moment:
![image](https://user-images.githubusercontent.com/30297881/131263878-3bd55aec-43d3-4226-be8c-937f91805a79.png)

It's not the best but maybe we should use that for the moment until we get a proper "revamp" of our TOC if we were to better display the current entry.
What do you think?

**Comment by phillxnet** [comment]
@FroggyFlox I think that's just find. As you say it works for now and keeps things simple so lets go with that.
Thanks.

**Comment by FroggyFlox** [comment]
Sounds good... a PR will follow soon, then.
