### ISSUE TITLE
User/Group permissions settings are not documented

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#347]
We currently do not have a dedicated section to illustrate and detail how to set user/group permissions on a share, although we do have some Rock-ons writeups documenting the process.

Despite the fact that this feature is very self-explanatory in the web-UI, it would be greatly beneficial to have a dedicated section to which we could refer from other parts of the documentation that indeed direct the user to set/adjust user/group permissions on a share.

Given our documentation is now organized to mirror Rockstor's webUI, it is proposed to add such documentation as a sub-section of the `shares-btrfs-subvolumes.rst` page.

**Comment by FroggyFlox** [comment]
@phillxnet , although I'm not an export on the matter, this issue has been creeping in my mind for a while and its resolution would greatly facilitate my current work on #110. I can thus get a PR out with at least the basics on the "Access control" tab of our webUI and we can always improve upon that later as needed. Would you be ok with that?

**Comment by phillxnet** [comment]
@FroggyFlox 
> I can thus get a PR out with at least the basics on the "Access control" tab of our webUI and we can always improve upon that later as needed. Would you be ok with that?

That would be great.

Also, as with some of my own doc pr's recently. If you need to merger and publish pre-review in order to reference / build-on, or what-ever then of course just go ahead. As long as they render OK via our buildbot local publish target first; as usual. If you could make a note that you are about to do that then it would help to avoid treading on each others toes.

Thanks for stepping up to this one. It does seem from recent forum events that we have some work to do on some of the basics.

Cheers.

**Comment by FroggyFlox** [comment]
Sounds good, thanks!
I'll get to it, then.
