### ISSUE TITLE
Add documentation describing DR situations

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#37]
A useful comment from HN

My very first questions regarding a potential storage solution revolve around data loss:

```
1. Can we enumerate the data loss scenarios?
2. How is drive failure handled?
3. How may data be corrupted and such corruption detected?
4. For every data loss scenario, what is the recovery procedure?
```

Here is all I could find: http://rockstor.com/docs/faq.html#how-do-i-prevent-data-loss...

Of course, there is a wealth of information on such questions for standard RAID, but I would suggest for marketing purposes that rockstor synthesize available information (from the many relevant layers of data management) in a coherent fashion, specific to their product. It doesn't have to be deep, but it should be at least minimally comprehensive and broad, with pointers to more detailed, layer-specific information.

Also, it's fine if the recovery scenario is "restore from backup" for e.g. the scenario where data is deleted by an authorized user. If so, there should be at least a minimal "backup story".

**Comment by phillxnet** [comment]
This issue was written prior to our now standard use of the elrepo kernel ie 4.10 as of writing and now fairly regularly updated.

Linking to related issue re pending improvements to our "Data loss Prevention and Recovery in Rockstor" section #167 "Improve loss prevention and recovery section" which specifies a particular short coming. And we have had additional improvements to this section in the mean time ie pr =143 "Rewrite raid56 recovery section to correct errors and remove redundan…".

**Comment by phillxnet** [comment]
Closing re no further attention and with reference to the improvements indicated by @schakrava  and those indicated in my last comment here 4 years ago.

N.B. we also now have Web-UI header warnings and 'wizards' re disk removal / degraded remount in-Web-UI for errors on or missing disk  scenarios.

Closing as part of a repo clean-up.
