### ISSUE TITLE
Rockstor updated itself to an "unsupported" kernel

### ISSUE THREAD

**Issue by cron410** [rockstor/rockstor-doc#38]
I have not run anything in the CLI of my test VM, only ran the WebUI update command. I received this error in the WebUI after my second reboot.

    You are running an unsupported kernel(3.10.0-123.20.1.el7.x86_64). Some features may not work properly. Please reboot and the system will automatically boot using the supported kernel(3.18.1-1.el7.elrepo.x86_64)

**Comment by phillxnet** [comment]
I had this, it seems that the second reboot after that particular update (to 3.18 I believe it was) caused a regression to the CentOS standard kernel of 3.10.  Mine reverted back to the intended / updated kernel after a subsequent reboot.  Also note that this issue is in rockstor-doc but would be more appropriate in rockstor-core (a mistake akin to what I just made myself).  I hope that your system like wise resolved this issue by itself.  There is now a further update that includes an additional kernel upgrade.

**Comment by phillxnet** [comment]
@schakrava I suspect this can now be closed as I haven't heard of or had this happen with any of the subsequent kernels / upgrades.
@cron410 Thanks for reporting, seems it's just been you and me on this one.  Hope you are happy with it being closed for now.

**Comment by schakrava** [comment]
Thanks @phillxnet

**Comment by phillxnet** [comment]
OK just had this happen again:-
Install was original from iso and had 3.8-0.2 (a strange one I know)
I then updated via WebUI to 3.8-1 and upon first reboot there after I was back at 3.10 kernel.
Howerver there was a warning to that effect and a subsequent reboot got me back to 4.0.2 without any intervention.  This was on real hardware.

**Comment by schakrava** [comment]
I've seen this behavior and the reason is this. When ever CentOS upstream releases a new kernel, it makes itself the default while installing. I haven't gotten a chance to test this out yet, but I think the solution is to put a "exclude=kernel*" in the updates section of /etc/yum.repos.d/CentOS-Base.repo

[updates]
name=CentOS-7 - Updates
mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=updates&infra=$infra
#baseurl=http://mirror.centos.org/centos/7/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
exclude=kernel*

I'd be interested to find out if it works by editing the file after install but before running the first update from the WebUI.

**Comment by phillxnet** [comment]
That sounds like a plausible candidate, especially since it's been so intermittent; I also saw more 3.10 kernels than I thought were there before as well. I'll look some more and give it a go and report back here.  Just a little worried as that revert is getting progressively more risky as we move on.

**Comment by cron410** [comment]
Is this related to the closed issues #557?



Regards,



*Charles Gunzelman*

(410) 713-9233

cron410@gmail.com

**Comment by phillxnet** [comment]
@cron410 it does look that way, grubby seems not to be the whole solution.  But if as @schakrava suggests the kernel is excluded from standard updates then we may be there on this one.  Maybe https://github.com/rockstor/rockstor-core/issues/557 should be re-opened and this issue referenced as then we can deal with it in the core repository where it belongs.  Thanks for the connection @cron410 I missed that one.

**Comment by phillxnet** [comment]
Test of proposed:-
exclude=kernel*
in [updates] repo config
A system where this inadvertent 3.10 kernel downgrade did happen now has the following additional kernel "Rockstor (3.10.0-229.7.2.e17.x86_64) 3 (Core)" along "with debugging" counterpart entry in grub.
On a system that does not have this additional 3.10 kernel a "yum update" shows it as ready to install. However if I then add the @schakrava suggested exclude=kernel* to the updates repo config then no kernel is suggested in a subsequent "yum update" output.  And this later "yum update" executes successfully.

**Comment by phillxnet** [comment]
Conversely executing a "yum update" on a system without this exclude command results in the subsequent boot auto selecting the 3.10.0-229.7.2.el7.x86_64 along with the resulting WebUI warning. The subsequent reboot results in the proper 4.0.2 being re-instated as the default.
@schakrava I say we squeeze this exclude into the next release as a kernel revert is not good, would this be a candidate for the rockstor-iso repo.

**Comment by phillxnet** [comment]
Just to keep track of this, although a fix is due in the next iso I believe.
This will happen on new builds via:-
clean 3.8-0.3 iso install:
hostname, admin, pass, update now dialog, and up to 3.8-2
gives unsupported kernel error as 3.8-2 now expects the 4.1 (and iso was in 4.0.2)
I think this message should also add - "Please reboot to use the recommended kernel."
Except on shutdown via the WebUI and first power up there after boots to 3.10 and the terminal was non responsive.
Although the subsequent boot (after vm shutdown) then re-asserts 4.1.0
Just noting here so we know it happens with fresh 3.8 iso upgrade to just released 3.8-2 upgrade.

**Comment by schakrava** [comment]
@phillxnet Thanks for driving this issue. Turns out no code changes to rockstor-core are required to solve this problem. It's just an update to rockstor-release package which I tested and pushed a few minutes ago. Now, unless users run a manual yum update and then update Rockstor via WebUI, they will still need to reboot first time around. But after that they will have exclude=kernel* change and subsequent updates will not pull kernel from CentOS repos.

Also, when we do create the next iso, this release package will automatically go in there.
