### ISSUE TITLE
Update/replace root password reset doc to v4+ "Built on openSUSE"

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#404]
Our following page: https://rockstor.com/docs/howtos/reset-root-password.html pertains only to our now legacy CentOS releases prior to V4 "Built on openSUSE". It would be nice to have a V4+ update or alternative and likely maintain the old v3 and earlier doc as a how-to explicitly adding there that it is for the now legacy v3- installs.

Note also that this doc is hard-url referenced from within rockstor-core here:

https://github.com/rockstor/rockstor-core/blob/ccd21f7703d8974282bc05d232efc8f8c67b7700/src/rockstor/storageadmin/templates/storageadmin/login.html#L143

**Comment by phillxnet** [comment]
@Hooverdan96 In our prior CentOS days we just used our upstream's installer to get a shell to do the password reset. I don't think our installer has this capability. But whatever works, that is relatively straightforward would be good here. I'm a little reluctant to add complexity to our existing installer (i.e. like an additional boot option for example) so yes, maybe we could resource an upstream mini-iso or the like to get to the filesystem, as that is all we need I think.

Haven't looked to what exactly is required however. And maybe we can invoke a rescue option that already exists in our kiwi-ng installer via for example a kernel/initram option or the like.

**Comment by Hooverdan96** [comment]
Just for posterity, this is how I have done it (a kiwi-ng option did not become apparent to me, and a mini-iso would of course add to the installation file).

Downloaded the appropriate rescue iso from here the live CD offerings on OpenSUSE - in this case 15.4 from here: https://download.opensuse.org/distribution/leap/15.4/live/ (around 0.6GiB in size).

In my case, trying this on a VM, so easy enough to just pop in the iso file, otherwise balena etcher onto a USB stick.

When booting from USB/VM virtual device, select select 2nd option to get to CLI:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/35113775/234396675-63685b38-1625-4c2e-a836-f76a732cc3a7.png">

After the boot is complete:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/35113775/234397120-9754b161-4e1d-4a17-a089-446820b89e9d.png">

enter `root` as login name, hit <Enter> and login complete.

Then I mostly followed the tutorial from here:
https://en.opensuse.org/SDB:Recover_root_password#CD/DVD/USB_recovery_mode

It does require a bit of knowledge what the devices represent, but for me it was using
`lsblk` which gave me an idea of - just based on size - which device I was looking for - `/dev/sda`, then and (again in my case) identified `/dev/sda4` as the item to mount.

the `remount` option gave me errors, so after dropping that and:
`mount -o rw /dev/sda4 /mnt` I followed the second set of instruction before executing `chroot`:
```
# mount -o bind /proc /mnt/proc
# mount -o bind /sys /mnt/sys
# mount -o bind /dev /mnt/dev
# chroot /mnt
# mount -a
# passwd
```

After removing the boot media and rebooting, the root password was changed on Rockstor ... so, that's one way of doing it, I guess?

**Comment by Hooverdan96** [comment]
I finally found, for a TW rescue disk the path is somewhat different, at least for `x86_64`
https://download.opensuse.org/tumbleweed/iso/, e.g.,
https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-Rescue-CD-x86_64-Current.iso

Not sure what to do in the arm64 or raspberry pi case here (incidentally for Leap I also didn't see a rescue image/approach for the pi).
