### ISSUE TITLE
Include reference to 'Open Collective' in Software Update documentation

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-doc#436]
Thanks to the question of forum member [@jihiggs](https://forum.rockstor.com/u/jihiggs) on appliance IDs, a needed clarification in the documentation became apparent.
https://forum.rockstor.com/t/will-there-be-a-simple-upgrade-when-the-next-version-is-stable/8810

In this section of the documentation:

https://rockstor.com/docs/interface/system/update_channels.html

Possibly include a mention of the Open Collective approach for stable channel subscriptions to clarify requirements and benefits for using that model. Currently there is still a link to the shop only (the shop currently only serving the purpose to get the Activation Code), it might be as simple as for now only repointing the store link to the Open Collective website as we have done on top of the Community Forum and inside the Rockstor Appliance. Or, it could be more elaborate with its own section describing the background/concept of Open Collective (as a second step).

Open to suggestions, maybe there is a better place to elaborate on this.

**Comment by phillxnet** [comment]
@Hooverdan96 I think we have this one covered now:

Re:
> repointing the store link to the Open Collective website

This has now been resolved via: "Resolve latest linkcheck issues #473" #475
- (sub-part) "Shop replaced by Open Collective - rough first pass."

For older installs we also have the following server implemented redirect of the prior Shopify subdomain:
- https://shop.rockstor.com to: https://rockstor.com/legacy-shop-info.html

So that the older Web-UI links and instructions are informed by that updated-instructions page.

Closing as:
Fixed by #475
